### ISSUE TITLE
Triggerring multiple builds

### ISSUE THREAD

**Issue by shinze** [mdvorscak/metalsmith-browser-sync#1]
Having a slow refresh with this plugin used. Looking at the build system it seems to trigger multiple builds as the build folder appears and disappears several times in file tree of Sublime Text when BS in running before it stays. Tried to move the BrowserSync after or before the build itself but it doesn’t have any effect.

**Comment by mdvorscak** [comment]
Hey @gaetanark, 

I think I've seen this issue before, but I'm not currently able to reproduce it. Do you have a link to the source where I can reproduce this? Or could you put you main metalsmith file in the comments? 

I did notice an issue where the build was occurring on every refresh (maybe that's the real issue?).

I'm currently working to integrate with a newer version of Browser-Sync (2.6.0), which would prevent builds from occurring on every request.   

Thanks,
Mike

**Comment by shinze** [comment]
Hi @mdvorscak 

Manual reloads or requests apparently triggers a re-build, but it seems so random that I'm not sure it’s the issue here. And on a simpler build the problem doesn’t occurs.

I created a copy of my project here so you can have a test case. https://github.com/gaetanark/temp.

Edit : The script inserted is browser-sync-client.2.6.4.js (isn't it ever the latest version ?).

**Comment by shinze** [comment]
I got a new message now : `FATAL ERROR: CALL_AND_RETRY_0 Allocation failed - process out of memory` and the process dies.
