### ISSUE TITLE
Consider displaying an error message if the build fails, even without debug set

### ISSUE THREAD

**Issue by mattly** [mdvorscak/metalsmith-browser-sync#13]
One of the items in my build process was failing because it had bad input. Where the non-browser-sync pipeline would have failed and output an error message, ms-browser-sync just tells me "[BS] Reloading Browsers..." without so much as a warning that something went wrong. I know there's an option available with debug to display the error, but showing the error should be the default. I shouldn't have to think "something's wrong here", quit and restart my process, and only _then_ find out my plugin is warning me of bad input.

**Comment by gabz75** [comment]
+1 on this
