### ISSUE TITLE
Callback was already called

### ISSUE THREAD

**Issue by franklinjavier** [mdvorscak/metalsmith-browser-sync#6]
When I try to use browserSync, I'm getting this error
This is my [index.js](https://github.com/franklinjavier/franklinjavier/blob/master/index.js)

Any suggestions to fix it?
Cheer

```
$ node index.js 
/home/franklin/b0x/Projects/blog/node_modules/metalsmith-templates/node_modules/async/lib/async.js:22
            if (called) throw new Error("Callback was already called.");
                              ^
Error: Callback was already called.
    at /home/franklin/b0x/Projects/blog/node_modules/metalsmith-templates/node_modules/async/lib/async.js:22:31
    at /home/franklin/b0x/Projects/blog/node_modules/metalsmith-templates/lib/index.js:63:25
    at Function.exports.handlebars.render (/home/franklin/b0x/Projects/blog/node_modules/metalsmith-templates/node_modules/consolidate/lib/consolidate.js:499:5)
    at /home/franklin/b0x/Projects/blog/node_modules/metalsmith-templates/node_modules/consolidate/lib/consolidate.js:146:25
    at /home/franklin/b0x/Projects/blog/node_modules/metalsmith-templates/node_modules/consolidate/lib/consolidate.js:99:5
    at fs.js:336:14
    at FSReqWrap.oncomplete (fs.js:99:15)

```

**Comment by claycarpenter** [comment]
This issue seems to have been fixed by my PR #5 .

If you want to give it a try on your site, you can use this command:

`npm install --save-dev git://github.com/claycarpenter/metalsmith-browser-sync#active-check`

**Comment by franklinjavier** [comment]
@claycarpenter thanks, but... Am I missing something?

```
npm install --save-dev git://github.com/claycarpenter/metalsmith-browser-sync#active-check
zsh: no matches found: git://github.com/claycarpenter/metalsmith-browser-sync#active-check
```

**Comment by franklinjavier** [comment]
Now it worked. I changed the contents manually and it worked.
I'll have repeat this process until our friend accepts your PR.
Thanks mate @claycarpenter

**Comment by claycarpenter** [comment]
@franklinjavier great! I was just going to reply that I couldn't replicate the error and suggest you make the changes manually. Glad to hear it's working for you.

**Comment by franklinjavier** [comment]
:beers:

**Comment by franklinjavier** [comment]
@claycarpenter every time I save a file, duplicates the quantity of posts.

**Comment by claycarpenter** [comment]
@franklinjavier As far as I can tell right now, this looks like an issue with metalsmith-collections when it's run multiple times without a fresh Metalsmith build. It's late and I'm sleepy and stupid, but it looks like the ms-collections plugin adds the matching files it finds to the global (Metalsmith) metadata each time it's run.

I made a very quick hack that fixed the problem by clearing out the metadata.posts collection before each metalsmith-collections run. The "plugin" looks like this:

```
    .use(function (files, metalsmith, done) {
        var metadata = metalsmith.metadata();
        delete metadata.posts;
        done();
    })
```

And should be inserted _before_ the metalsmith-collections plugin in the pipeline. I'm not saying this is a smart hack, but it should get you going for the time being.

Considering this issue probably isn't the fault of this metalsmith-browser-sync plugin, we should probably move the conversation over to your repo if you want to continue.

**Comment by franklinjavier** [comment]
Thanks for the solution.
